version: '2.2'
services:
  v2ray:
    image: "v2ray/official"
    restart: always
    hostname: "v2ray"
    volumes:
    - ./v2ray/server.json:/etc/v2ray/config.json
    - /etc/localtime:/etc/localtime:ro


  nginx:
    image: "nginx"    
    restart: always
    hostname: "nginx"
    volumes:
    - ./nginx/conf:/etc/nginx
    - ./nginx/log:/var/log/nginx
    ports:
    - "23143:80"
